Fix missing header for size_t
liteserver/binn pull request #39
Opened 2021-05-29 16:15 UTC by funbiscuit

Without this standard C header it doesn't compile with following error:

`src\binn.h(259): error C2081: 'size_t': name in formal parameter list illegal`

Library itself (`binn.c`) compiles normally because it includes other standard headers before `binn.h` so `binn.h` receives `size_t` definition. But if you include `binn.h` in some other C file (like in `writing.c`) and don't include other headers, it won't compile.
`stddef.h` is standard header so I think it should be okay to include that. All compilers should support it.

2024-01-31 03:17 UTC, kroggen requested changes

2024-01-31 03:18 UTC, kroggen commented on src/binn.h
> +
This comment above was marked as "pending" on GitHub since 2021!
I have not perceived that it was not appearing to other users

2024-02-21 11:44 UTC, funbiscuit commented on src/binn.h
> +
Moved include below

2024-02-21 18:29 UTC, kroggen commented
I never needed this include
You can see the tests run fine without it
Is this happening in a specific platform?
Which compiler are you using?
In which OS?

2024-02-22 02:30 UTC, merged

2024-02-22 02:31 UTC, kroggen commented
OK, Thanks!